api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

services:
    todo.is_completed_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { isCompleted: ~ } ]
        tags: [ 'api_platform.filter' ]

    todo.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [ { createdAt: ~, completedAt: ~ } ]
        tags: [ 'api_platform.filter' ]
